import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Link, Outlet, useNavigate } from 'react-router-dom';
import Footer from '../molecules/Footer';
import ContactFormWidget from '../molecules/ContactFormWidget';
const home = () => {
    const navigate = useNavigate();
    return (_jsx(_Fragment, { children: _jsxs("div", { className: 'flex flex-col items-center justify-between flex-nowrap h-full max-w-screen', children: [_jsx("header", { className: "w-full mt-1 text-gray-700 bg-white shadow-sm body-font relative ", children: _jsxs("div", { className: "container flex items-center justify-between p-2 mx-auto max-w-full", children: [_jsx(Link, { to: "/", className: "flex items-center font-medium text-gray-900 title-font md:mb-0", children: _jsx("img", { src: "./logo.png", alt: "logo", className: "w-20 " }) }), _jsxs("nav", { className: "flex-nowrap items-center justify-center pl-6 ml-6 text-base border-l hidden sm:flex border-gray md:mr-auto ", children: [_jsx(Link, { to: "/", className: "mr-5 font-medium hover:text-gray-900", children: "Home" }), _jsx(Link, { to: "/my-work", className: "mr-5 font-medium hover:text-gray-900", children: "My Work" }), _jsx(Link, { to: "/about", className: "mr-5 font-medium hover:text-gray-900", children: "About Me" }), _jsx(Link, { to: "/contact", className: "font-medium hover:text-gray-900", children: "Contact" })] }), _jsxs("div", { className: "flex flex-nowrap items-center h-full justify-end mx-2", children: [_jsx("button", { onClick: () => navigate("/login"), className: "mr-5 font-medium hover:text-gray-900", children: "Login" }), _jsx("button", { onClick: () => navigate("/signup"), className: "px-4 py-2 text-xs font-bold text-white uppercase transition-all duration-150 bg-green-500 rounded shadow outline-none active:bg-green-600 hover:shadow-md focus:outline-none ease", children: "Sign Up" })] })] }) }), _jsxs("div", { className: "h-full max-w-full relative ", children: [_jsx(Outlet, {}), _jsx(ContactFormWidget, {})] }), _jsx("div", { className: 'relative mt-2 w-full', children: _jsx(Footer, {}) })] }) }));
};
export default home;
