import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import Icon from '@mdi/react';
import { mdiMenu } from '@mdi/js';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
const Header = (props) => {
    const [logo, setLogo] = useState('');
    useEffect(() => {
        setLogo('/logo.png');
    }, []);
    return (_jsx(_Fragment, { children: _jsxs("header", { className: "flex w-full items-center justify-between border-b-2 border-gray-100 bg-white p-2", children: [_jsxs("div", { className: "flex items-center space-x-2 pl-2", children: [_jsx("button", { type: "button", className: "text-3xl", onClick: () => { props.setASideOpen(!props.aSideOpen); }, children: _jsx(Icon, { path: mdiMenu, size: 1 }) }), _jsx(Link, { to: '/', className: 'w-20', children: _jsx("img", { src: logo, className: 'w-20 h-10', alt: "" }) })] }), _jsxs("div", { className: 'flex items-center space-x-4', children: [_jsx("div", { className: 'cursor-pointer', children: _jsx("svg", { xmlns: "http://www.w3.org/2000/svg", className: "w-5 h-5 mx-1", viewBox: "0 0 20 20", fill: "currentColor", children: _jsx("path", { d: "M3 1a1 1 0 000 2h1.22l.305 1.222a.997.997 0 00.01.042l1.358 5.43-.893.892C3.74 11.846 4.632 14 6.414 14H15a1 1 0 000-2H6.414l1-1H14a1 1 0 00.894-.553l3-6A1 1 0 0017 3H6.28l-.31-1.243A1 1 0 005 1H3zM16 16.5a1.5 1.5 0 11-3 0 1.5 1.5 0 013 0zM6.5 18a1.5 1.5 0 100-3 1.5 1.5 0 000 3z" }) }) }), _jsx("button", { type: "button", className: "h-9 w-9 overflow-hidden rounded-full flex justify-center", onClick: () => { props.setProfileDiv(!props.profileDiv); }, children: _jsx("img", { src: props.profileImageUrl, alt: "profile-img" }) }), _jsxs("div", { className: ["absolute right-2 mt-64 w-48 divide-y divide-gray-100 rounded-md border border-gray bg-white shadow-md", props.profileDiv ? "" : " hidden"].join(""), children: [_jsxs("div", { className: "flex items-center space-x-2 p-2", children: [_jsx("img", { src: props.profileImageUrl, alt: "profile-img", className: "h-9 w-9 rounded-full" }), _jsx("div", { className: "font-medium", children: "Hafiz Haziq" })] }), _jsxs("div", { className: "flex flex-col space-y-3 p-2", children: [_jsx(Link, { to: "profile", className: "transition hover:text-blue-600", children: "My Profile" }), _jsx(Link, { to: '', className: "transition hover:text-blue-600", children: "Edit Profile" }), _jsx(Link, { to: '', className: "transition hover:text-blue-600", children: "Settings" })] }), _jsx("div", { className: "p-2", children: _jsxs("button", { className: "flex items-center space-x-2 transition hover:text-blue-600", children: [_jsx("svg", { className: "h-4 w-4", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", xmlns: "http://www.w3.org/2000/svg", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: "2", d: "M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" }) }), _jsx("div", { children: "Log Out" })] }) })] })] })] }) }));
};
export default Header;
